[package]
name = "wan"
version = "0.0.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]

[dependencies]
curl = { git = "https://github.com/ubnt-intrepid/curl-rust.git", branch = "pkg-config" }
env_logger = "*"
log = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
error-chain = "*"
clap = "*"
shlex = "*"
