# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end

  config.vm.box = "fedora/25-cloud-base"
  config.vm.provider :virtualbox do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.synced_folder ".", "/vagrant",
    type: "rsync",
    rsync__args: ["--verbose", "--archive", "--delete", "--copy-links", "--times", "-z"],
    rsync__exclude: [".git/"]

  config.vm.provision :docker
  config.vm.provision :docker_compose,
    yml: "/vagrant/docker-compose.yml",
    run: "always",
    rebuild: true
end
